version: "3.7"

services:
  managedhost-app-1:
    build: 
      context: managed-host/alpine/app1
    restart: unless-stopped
    ports:
      - "3000:3000"  # Map Container port 3000 to Host port 3000 (Web)
      - "2223:22"    # Map Container port 22 to Host port 2223 (SSH)
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_app1.pub:/root/.ssh/authorized_keys  # Mount public key specific to managedhost-app-1

  managedhost-app-2:
    build: 
      context: managed-host/alpine/app2
    restart: unless-stopped
    ports:
      - "3001:3000"  # Map Container port 3000 to Host port 3001 (Web)
      - "2224:22"    # Map Container port 22 to Host port 2224 (SSH)
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_app2.pub:/root/.ssh/authorized_keys  # Mount public key specific to managedhost-app-2

  managedhost-app-3:
    build: 
      context: managed-host/alpine/app3
    restart: unless-stopped
    ports:
      - "3002:3000"  # Map Container port 3000 to Host port 3002 (Web)
      - "2225:22"    # Map Container port 22 to Host port 2225 (SSH)
    environment:
      - SSH_ENABLE_ROOT=true
    volumes:
      - ./secrets/id_rsa_app3.pub:/root/.ssh/authorized_keys  # Mount public key specific to managedhost-app-3