all:
  children:
    ungrouped:
      hosts:
        managedhost-app-1:
          ansible_host: 0.0.0.0
          ansible_connection: ssh
          ansible_port: 2223  # Check the SSH port mapping in docker-compose.yml
          ansible_user: root

        managedhost-app-2:
          ansible_host: 0.0.0.0
          ansible_connection: ssh
          ansible_port: 2224  # Check the SSH port mapping in docker-compose.yml
          ansible_user: root

        managedhost-app-3:
          ansible_host: 0.0.0.0
          ansible_connection: ssh
          ansible_port: 2225  # Check the SSH port mapping in docker-compose.yml
          ansible_user: root

    app_group:
      hosts:
        managedhost-app-1:
        managedhost-app-2:
        managedhost-app-3:
